name: Build MS Docker Image

on: 
  workflow_dispatch:

jobs:        
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push master-server docker
      uses: docker/build-push-action@v2
      with:
        context: ./Source/MasterServer/
        file: ./Source/MasterServer/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ds3os-master:latest 
